spring.config.import=optional:file:.env[.properties]

spring.application.name=${APP_NAME:auth-service}

server.port=${SERVER_PORT:8086}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging.file.name=${LOG_FILE_NAME:logs/auth-service.log}
logging.level.com.pamperpaw.auth=INFO
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
