spring.config.import=optional:file:.env[.properties]

spring.application.name=${APP_NAME:customer-service}

server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
logging.level.org.springframework=INFO
logging.level.com.pamperpaw.customer=INFO
logging.file.name=${LOG_FILE_NAME:logs/customer-service.log}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
