spring.config.import=optional:file:.env[.properties]

spring.application.name=${APP_NAME:payment-service}
server.port=${SERVER_PORT:8088}

internal.service.key=${INTERNAL_SERVICE_KEY:pamper-paws-internal-dev-key}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

razorpay.key-id=${RAZORPAY_KEY_ID:}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:}
razorpay.currency=${RAZORPAY_CURRENCY:INR}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
logging.file.name=${LOG_FILE_NAME:logs/payment-service.log}
logging.level.com.pamperpaw.payment=INFO
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
