spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:8761}

spring.application.name=${APP_NAME:discovery-server}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
logging.file.name=${LOG_FILE_NAME:logs/discovery-server.log}
logging.level.com.pamperpaw.discovery=INFO
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
